export const masters: Master[] = [
  "Starwars",
  "Startrek",
  "Got",
  "Elvish",
  "All",
  "Yoda",
  "Pirate",
  "Valspeak",
  "Minion",
  "Ferb-latin",
  "Pig-latin",
  "Dothraki",
  "Valyrian",
  "Hodor",
  "Sindarin",
  "Quenya",
  "Orcish",
  "Sith",
  "Cheunh",
  "Gungan",
  "Mandalorian",
  "Huttese",
  "Chef",
  "Catalan",
  "Oldenglish",
  "Shakespeare",
  "Vulcan",
  "Klingon",
  "Romulan",
  "Dovahzul",
  "Thuum",
  "Aldmeris",
  "Groot",
  "Jive",
  "Ebonics",
  "Dolan",
  "Fudd",
  "Kraut",
  "Wow",
  "Cockney",
  "Norfolk",
  "Morse",
  "Us2uk",
  "Uk2us",
  "Leetspeak",
  "Brooklyn",
  "Ermahgerd",
  "Australian",
  "Boston",
  "Austrian",
  "Article_rewrite",
  "Braille",
  "Numbers",
  "Emoji",
  "Doge",
  "Navi",
  "Southern-accent",
  "Ubbi-dubbi",
  "Inflationary-english",
  "George-bush-dubya",
  "Post-modern",
  "Ayleidoon",
  "Redneck",
  "Roman-numerals",
  "Asian-accent",
  "Russian-accent",
  "English-contraction",
  "Irish",
  "British",
  "German-accent",
  "Draconic",
  "Enderman",
  "Wheel-of-time-old-tongue",
];
export const sentences: string[] = [
  "Here's looking at you, kid.",
  "May the Force be with you.",
  "I'll be back.",
  "To infinity and beyond!",
  "There's no place like home.",
  "Here's Johnny!",
  "You can't handle the truth!",
  "I feel the need... the need for speed.",
  "Just keep swimming.",
  "You talking to me?",
  "Why so serious?",
  "I'm the king of the world!",
  "Life is like a box of chocolates.",
  "Keep your friends close, but your enemies closer.",
  "Houston, we have a problem.",
  "Say hello to my little friend!",
  "I coulda been a contender.",
  "Go ahead, make my day.",
  "I am Iron Man.",
  "I see dead people.",
  "It's alive! It's alive!",
  "Here comes the Men in Black.",
  "I am your father.",
  "There's no crying in baseball.",
  "I'm king of the world!",
  "That'll do, pig. That'll do.",
  "I'm not bad. I'm just drawn that way.",
  "Nobody puts Baby in a corner.",
  "Here's to you, Mrs. Robinson.",
  "To the stars and beyond!",
  "I'm flying, Jack!",
  "I'm Batman.",
  "I'll make him an offer he can't refuse.",
  "Say 'hello' to my little friend!",
  "Wax on, wax off.",
  "I have a bad feeling about this.",
  "I see you.",
  "I am Groot.",
  "I am the danger.",
  "It's not a tumor!",
  "I'm the Dude. So that's what you call me.",
  "You are a wizard, Harry.",
  "I could dance with you till the cows come home.",
  "I volunteer as tribute!",
  "I am Spartacus!",
  "I am McLovin.",
  "I am Jack's complete lack of surprise.",
  "I'm ready for my close-up, Mr. DeMille.",
];
